

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Service
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ModelDataBaseContainer : DbContext
{
    public ModelDataBaseContainer()
        : base("name=ModelDataBaseContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Subscription> Subscriptions { get; set; }

}

}

