
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Service
{

using System;
    using System.Collections.Generic;
    
public partial class Subscription
{

    public int Id { get; set; }

    public int WorkOutsAmount { get; set; }

    public int WorkOutsPassed { get; set; }

    public decimal Price { get; set; }

    public System.DateTime DateCreateSubscription { get; set; }

    public Nullable<System.DateTime> LastWorkOutDateTime { get; set; }



    public virtual Client Client { get; set; }

}

}
